version: '3'

services:
    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'
        expose:
            - '5432'
        environment:
            - POSTGRES_USER=journali
            - POSTGRES_PASSWORD=journali
            - POSTGRES_DB=journali
        volumes:
            - 'dbdata:/var/lib/postgresql/data'
    traefik:
        # The official v2 Traefik docker image
        image: traefik:v2.1
        # Enables the web UI and tells Traefik to listen to docker
        ports:
            # The HTTP port
            - '80:80'
            # The Web UI (enabled by --api.insecure=true)
            - '8080:8080'
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/etc/traefik/traefik.toml
    api:
        build:
            context: .
            dockerfile: api.dockerfile
        image: docker.pkg.github.com/journalio/test-rocket-app/api:latest
        env_file: .env.docker
        stop_signal: SIGINT
        expose:
            - '8000'
        labels:
            - 'traefik.http.routers.app.rule=(Host(`app.test`) && PathPrefix(`/api/`))'
    web:
        build:
            context: .
            dockerfile: web.dockerfile
        image: docker.pkg.github.com/journalio/test-rocket-app/web:latest
        expose:
            - '80'
        volumes:
            - ./public:/usr/share/nginx/html
        labels:
            - 'traefik.http.routers.api.rule=Host(`app.test`)'

volumes:
    dbdata:
